### ISSUE TITLE
Parse errors

### ISSUE THREAD

**Issue by JordanLeich** [ThreeGiantNoobs/chegg-scraper#23]
I have done all of the instructions in the readme and installed all of the requirements but I keep getting this error message - cheggscraper.Exceptions.FailedToParseAnswer. Here are the two chegg questions I tried to answer but got errors.
https://www.chegg.com/homework-help/questions-and-answers/-following-code-example-type-css-rule-h3-color-blue-id-html-selector-class-compound-q28240766
https://www.chegg.com/homework-help/questions-and-answers/math-problem-q4908624

**Comment by JordanLeich** [comment]
Here is the entire error message pasted.
Enter url of the homework-help: https://www.chegg.com/homework-help/questions-and-answers/math-problem-q4908624
Traceback (most recent call last):
  File "C:\Users\Jordan Leich\Downloads\Python Programs\chegg-scraper-1.3\chegg-scraper-1.3\Downloader.py", line 3, in <module>
    Downloader.main()
  File "C:\Users\Jordan Leich\Downloads\Python Programs\chegg-scraper-1.3\chegg-scraper-1.3\cheggscraper\Downloader.py", line 40, in main
    print(Chegg.url_to_html(args['url'], file_name_format=args['file_format']))
  File "C:\Users\Jordan Leich\Downloads\Python Programs\chegg-scraper-1.3\chegg-scraper-1.3\cheggscraper\CheggScraper.py", line 521, in url_to_html
    headers, heading, question_div, answers__, question_uuid = self._parse(html_text=html_res_text,
  File "C:\Users\Jordan Leich\Downloads\Python Programs\chegg-scraper-1.3\chegg-scraper-1.3\cheggscraper\CheggScraper.py", line 455, in _parse
    answers_div = self._parse_answer(soup, questionUuid, html_text, url, chapter_type=chapter_type)
  File "C:\Users\Jordan Leich\Downloads\Python Programs\chegg-scraper-1.3\chegg-scraper-1.3\cheggscraper\CheggScraper.py", line 387, in _parse_answer
    raise FailedToParseAnswer
cheggscraper.Exceptions.FailedToParseAnswer

Process finished with exit code 1

**Comment by PrathakGarg** [comment]
Are you using a premium chegg account?

**Comment by JordanLeich** [comment]
> Are you using a premium chegg account?

I just tested and yes, it seems to only work with a premium paid Chegg account. It will not work with a Chegg account that isn't paid for unfortunately.

**Comment by PrathakGarg** [comment]
👍🏻
