### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shery3101** [ThreeGiantNoobs/chegg-scraper#44]
Got this error while trying to scrape a URL
`Traceback (most recent call last):
  File "/Users/sheheryartariq/Downloads/chegg-scraper-1.3/Downloader.py", line 3, in <module>
    Downloader.main()
  File "/Users/sheheryartariq/Downloads/chegg-scraper-1.3/cheggscraper/Downloader.py", line 40, in main
    print(Chegg.url_to_html(args['url'], file_name_format=args['file_format']))
  File "/Users/sheheryartariq/Downloads/chegg-scraper-1.3/cheggscraper/CheggScraper.py", line 521, in url_to_html
    headers, heading, question_div, answers__, question_uuid = self._parse(html_text=html_res_text,
  File "/Users/sheheryartariq/Downloads/chegg-scraper-1.3/cheggscraper/CheggScraper.py", line 437, in _parse
    re.search(r'C\.page\.homeworkhelp_question\((.*)?\);', html_text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by bayramj** [comment]
I am getting the same issue, were you able to resolve this?

**Comment by Injest** [comment]
I am also pulling the same error.  How did you solve it?

**Comment by lylybay** [comment]
Same error……anyone there could help?
