### ISSUE TITLE
run

### ISSUE THREAD

**Issue by Skyfz** [ThreeGiantNoobs/chegg-scraper#7]
chegg-scraper>python Downloader.py
Enter url of the homework-help: https://www.chegg.com/homework-help/questions-and-answers/bicycle-pedal-crank-subjected-1000-n-pedaling-force-determine-torque-nm-point-b--dimension-q30751129
Traceback (most recent call last):
  File "chegg-scraper\Downloader.py", line 28, in <module>
    print(Chegg.url_to_html(args['url'], file_path=args['file_path']))
  File "chegg-scraper\CheggScraper.py", line 261, in url_to_html
    final_html, heading = self._parse(html_text=html_res_text)
  File "chegg-scraper\CheggScraper.py", line 243, in _parse
    answers__ = self._parse_answer(soup, html_text)
  File "chegg-scraper\CheggScraper.py", line 196, in _parse_answer
    _, question_data = self.parse_json(re.search(r'C.page.homeworkhelp_question\((.*)?\);', html_text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

chegg-scraper>python Downloader.py
Enter url of the homework-help: https://www.chegg.com/homework-help/questions-and-answers/bicycle-pedal-crank-subjected-1000-n-pedaling-force-determine-torque-nm-point-b--dimension-q30751129
Traceback (most recent call last):
  File "chegg-scraper\Downloader.py", line 28, in <module>
    print(Chegg.url_to_html(args['url'], file_path=args['file_path']))
  File "chegg-scraper\CheggScraper.py", line 261, in url_to_html
    final_html, heading = self._parse(html_text=html_res_text)
  File "chegg-scraper\CheggScraper.py", line 243, in _parse
    answers__ = self._parse_answer(soup, html_text)
  File "chegg-scraper\CheggScraper.py", line 208, in _parse_answer
    raise Exception
Exception

**Comment by Skyfz** [comment]
please assist
Is Paid Plan required?
regards
mike

**Comment by k4anubhav** [comment]
Yes, the Paid plan is required

You need to put your paid plan cookies in cookies.txt
